### ISSUE TITLE
Remove spacing in Ghana Dedicated Internet

### ISSUE THREAD

**Issue by dataguy23us** [telecom4good/telecom4good.github.io#25]
1.	Remove the space in the Ghana Dedicated Internet above Learn More so that each of the 3 boxes look the same spacing
2.	Choose between READ MORE under each or use the LEARN MORE (yellow bottom above) to make constant

![cap34](https://cloud.githubusercontent.com/assets/20802030/17529270/8d80e724-5e27-11e6-9357-01dbc930f1da.png)

**Comment by ariperez** [comment]
So that was a good catch.  I did add the extra space after Ghana in an attempt to keep the buttons consistent, but it obviously doesn't work on all screen types.  

I personally recommend the "Learn More" type button so the spacing is consistent. 
![image](https://cloud.githubusercontent.com/assets/2553469/17538051/eaac805a-5e6f-11e6-974d-8fc848206580.png)

 I'm going to remove that space after Ghana now so you can see what it would look like with the buttons. 

Let me know.

**Comment by dataguy23us** [comment]
Thank you
